### PR TITLE
Issue #110B: Alternate approach for JDK11

### PR DESCRIPTION
**Pull request by aclarkxyz**
Addresses issue #110 

I went for a simpler strategy of copying the JavaFX JAR files into the main directory and linking them at compile time. Works fine for either JDK 8 or 11. Runs fine with JDK 8 without any modification. For JDK 11, it can be run with this script:

```
setenv CP libjfx/javafx-swt.jar:libjfx/javafx.base.jar:libjfx/javafx.controls.jar:libjfx/javafx.fxml.jar:libjfx/javafx.graphics.jar:libjfxjavafx.media.jar:libjfx/javafx.swing.jar:libjfx/javafx.web.jar
setenv CP ${CP}:pkg/BioAssayTemplate.jar
setenv JAVA /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin
setenv JFX /opt/javafx-sdk-11.0.1/lib
$JAVA/java --module-path $JFX --add-modules=javafx.controls -cp $CP com.cdd.bao.Main
```

Biggest problem is that I can't get it to launch from Eclipse, either 2018-06 or 2018-12.

### CODE REVIEW

**Comment by philippcheung** [comment]
Finally got around to doing the latest pull and updating.  This is probably already in here, but for some reason my junit tests started to fail after I messed around with my JDK, so I had to follow this advice:

Basically, I had to copy over my junit and opentest jars into the my ant lib.

https://stackoverflow.com/questions/51697471/junit-5-with-ant-junitlauncher-noclassdeffounderror-org-junit-platform-launche

**Comment by philippcheung** [comment]
I'm still seeing failures in my Junit tests -- is there a specific database build I should be using?

**Comment by philippcheung** [comment]
[junitlauncher]   FAILED: testPermissive()
[junitlauncher]     expected: <2> but was: <1>
[junitlauncher]       com.cdd.bae.rest.FindIdentifierTest.testPermissive(FindIdentifierTest.java:94)

**Comment by gedeck** [comment]
Check your identifier.json file. It should be 
```
[
        {
                "name": "PubChem Assay ID",
                "shortName": "AID",
                "prefix": "pubchemAID:",
                "baseURL": "https://pubchem.ncbi.nlm.nih.gov/bioassay/"
        },
        {
                "name": "UCSF Assay ID",
                "shortName": "UCSF",
                "prefix": "ucsfAID:",
                "baseURL": ""
        },
        {
                "name": "Astra Zeneca ID",
                "shortName": "AZ",
                "prefix": "azID:",
                "baseURL": ""
        }
]
```
I think the AZ block is not required, however the UCSF is required for the test to work.

**Comment by gedeck** [comment]
The file `test/README.md` describes the requirement to copy the jar files to the ant lib.

**Pull request merged**
